/**
 * Tile grid storage. W × H grid of per-tile data.
 *
 * Per-tile fields:
 * - elevation: number (world units; 0 = ground level)
 * - biome:     small enum uint8 (0=grass, 1=dirt, 2=stone, 3=sand)
 * - occupancy: uint8; nonzero = a world entity (tree, rock, building) blocks the tile.
 *              Transient — NOT serialized; rebuilt from entities on load.
 * - stockpile: uint8; nonzero = player-designated stockpile tile. Serialized.
 * - wall:      uint8; nonzero = finished wall blocks the tile. Serialized.
 *              Separate from occupancy so we can differentiate "wall" vs
 *              "tree" in pathing + hydration without entity lookups.
 * - door:      uint8; nonzero = finished door on the tile. Doors are
 *              WALKABLE — `isBlocked` does not check this — they exist as a
 *              bitmap only so designators can reject double-placement.
 *              Serialized.
 * - torch:     uint8; nonzero = finished torch on the tile. Torches are
 *              decorative, non-blocking, and walkable. Stored as a bitmap so
 *              designators can reject double-placement without scanning
 *              entities. Serialized.
 * - roof:      uint8; nonzero = finished roof on the tile. Roofs don't affect
 *              pathing — they sit above the tile and block sunlight so the
 *              tile under them gets 0% sun. Bitmap so placement checks don't
 *              need entity lookups. Serialized.
 * - ignoreRoof: uint8; nonzero = player designated "don't auto-roof this tile".
 *              Auto-roof skips these. Serialized.
 * - floor:     uint8; nonzero = finished floor on the tile. Floors are
 *              walkable, non-blocking ground-layer tiles. Cows move at 100%
 *              speed on floors and 85% off them (before lighting modifiers).
 *              Serialized.
 * - light:     uint8; 0..255 mapping to 0..100% tile illumination. Derived
 *              from sun% and torches by the lighting system — NOT serialized.
 *              Cows move at half speed on tiles with light below 40%.
 * - farmZone:  uint8; 0 = not a farm tile, 1=corn, 2=carrot, 3=potato. Single
 *              field so zone membership + crop choice share storage; the
 *              non-zero value *is* the desired crop. Serialized.
 * - tilled:    uint8; nonzero = soil has been worked into planting rows.
 *              Independent of farmZone so an un-zoned tilled tile still
 *              renders as soil (e.g. after un-zoning a planted patch).
 *              Serialized.
 * - flower:    uint8; 0 = none, 1..N = flower kind (see world/flowers.js).
 *              Pure decoration — rolled at terrain-gen on a fraction of grass
 *              tiles, rendered as an instanced billboard. Skipped at render
 *              time if the tile has gained a wall/floor/tilled/farmZone since
 *              gen. Serialized.
 * - ramp:      uint8; nonzero = a ramp sits on this tile, slope going up to
 *              the layer above. Gives cross-layer pathing a single walkable
 *              tile to transition through — walking onto a ramp from below
 *              rises to z+1, from above descends to z-1. On the upper layer
 *              the ramp's footprint counts as an implicit floor at (i,j),
 *              so pathfinder sees the top of the ramp as walkable too.
 *              Serialized.
 */

import { TILE_SIZE } from './coords.js';

export const BIOME = Object.freeze({
  GRASS: 0,
  DIRT: 1,
  STONE: 2,
  SAND: 3,
  SHALLOW_WATER: 4,
  DEEP_WATER: 5,
});

/**
 * Vertical resolution of the terrain heightmap. Elevation is always a
 * non-negative multiple of this. One step = half a tile (0.75m). Cows
 * hop one step for free-ish; two steps (1.5m) require a slow climb; three
 * or more is blocked — see pathfinding.js for the exact thresholds.
 * Consumers that need "one floor up" should use `LAYER_HEIGHT`.
 */
export const TERRAIN_STEP = TILE_SIZE / 2;
/** Height of one Z-layer in world units (3m) — four terrain steps tall. */
export const LAYER_HEIGHT = TERRAIN_STEP * 4;
/** Maximum terrain step count generated by `generateTerrain`. 0..this inclusive. */
const MAX_TERRAIN_STEPS = 16;
/**
 * Width of the decorative skirt that extends the heightmap and biome field
 * beyond the playable grid so lakes + hills don't terminate in a sharp
 * straight line at the map edge. Skirt tiles are rendered but not pathable,
 * clickable, or otherwise interactive — `inBounds` and the picker still
 * clamp to the inner W×H.
 */
export const SKIRT_TILES = 8;

/** Tiles cows can wade across at swim speed; deep water blocks pathing entirely. */
export function isWaterBiome(b) {
  return b === BIOME.SHALLOW_WATER || b === BIOME.DEEP_WATER;
}

/**
 * Erode sand → shallow water: any sand tile with an unbroken 2-tile-thick sand
 * buffer in all directions (full 5×5 sand neighborhood, Chebyshev distance
 * from non-sand > 2) flips to SHALLOW_WATER. The 2-tile sand ring that
 * survives is the shore. Mutates the biome buffer in place. Shared between
 * `generateTerrain()` (new worlds) and the v31→v32 migration (old saves) —
 * its semantics are FROZEN so old saves replay deterministically.
 * @param {Uint8Array | number[]} biome
 * @param {number} W
 * @param {number} H
 */
export function carveWaterLakes(biome, W, H) {
  // Two-pass: read from `biome`, write into `out`, then commit. Prevents a
  // converted water tile from disqualifying its still-unscanned neighbors.
  const out = typeof biome.slice === 'function' ? biome.slice() : Array.from(biome);
  for (let j = 2; j < H - 2; j++) {
    for (let i = 2; i < W - 2; i++) {
      const k = j * W + i;
      if (biome[k] !== BIOME.SAND) continue;
      let allSand = true;
      for (let dj = -2; dj <= 2 && allSand; dj++) {
        for (let di = -2; di <= 2; di++) {
          if (biome[(j + dj) * W + (i + di)] !== BIOME.SAND) {
            allSand = false;
            break;
          }
        }
      }
      if (allSand) out[k] = BIOME.SHALLOW_WATER;
    }
  }
  for (let k = 0; k < biome.length; k++) biome[k] = out[k];
}

/**
 * Promote interior shallow water → deep water. Any shallow tile with an
 * unbroken 6-tile-thick shallow-water buffer (full 13×13 shallow neighborhood,
 * Chebyshev distance from non-shallow > 6) flips to DEEP_WATER. That leaves
 * exactly 6 rings of shallow water between shore and deep — the wade zone.
 * Mutates the biome buffer in place. Shared between `generateTerrain()` and
 * the v32→v33 migration.
 * @param {Uint8Array | number[]} biome
 * @param {number} W
 * @param {number} H
 */
export function carveDeepWater(biome, W, H) {
  const out = typeof biome.slice === 'function' ? biome.slice() : Array.from(biome);
  for (let j = 6; j < H - 6; j++) {
    for (let i = 6; i < W - 6; i++) {
      const k = j * W + i;
      if (biome[k] !== BIOME.SHALLOW_WATER) continue;
      let allShallow = true;
      for (let dj = -6; dj <= 6 && allShallow; dj++) {
        for (let di = -6; di <= 6; di++) {
          if (biome[(j + dj) * W + (i + di)] !== BIOME.SHALLOW_WATER) {
            allShallow = false;
            break;
          }
        }
      }
      if (allShallow) out[k] = BIOME.DEEP_WATER;
    }
  }
  for (let k = 0; k < biome.length; k++) biome[k] = out[k];
}

export class TileGrid {
  /**
   * @param {number} W
   * @param {number} H
   */
  constructor(W, H) {
    this.W = W;
    this.H = H;
    this.elevation = new Float32Array(W * H);
    this.biome = new Uint8Array(W * H);
    this.occupancy = new Uint8Array(W * H);
    this.stockpile = new Uint8Array(W * H);
    this.wall = new Uint8Array(W * H);
    this.door = new Uint8Array(W * H);
    this.torch = new Uint8Array(W * H);
    this.roof = new Uint8Array(W * H);
    this.ignoreRoof = new Uint8Array(W * H);
    this.floor = new Uint8Array(W * H);
    this.light = new Uint8Array(W * H);
    this.farmZone = new Uint8Array(W * H);
    this.tilled = new Uint8Array(W * H);
    this.flower = new Uint8Array(W * H);
    this.ramp = new Uint8Array(W * H);
    // Extended (skirted) biome + elevation buffers. Sized (W+2S)×(H+2S)
    // where S = SKIRT_TILES. Populated by `generateTerrain`; empty and
    // unused after a save-load until the caller re-runs generateTerrain.
    // `hasSkirt` is the flag the renderer uses to decide whether to draw
    // the decorative ring or fall back to W×H-only output.
    this.skirtW = W + 2 * SKIRT_TILES;
    this.skirtH = H + 2 * SKIRT_TILES;
    this.skirtBiome = new Uint8Array(this.skirtW * this.skirtH);
    this.skirtElevation = new Float32Array(this.skirtW * this.skirtH);
    this.hasSkirt = false;
    // Derived counters + torch index — maintained in the setters so lighting
    // can skip its full-grid sweep. Call `recomputeCounts()` after any bulk
    // write that bypasses the setters (e.g. save load).
    this.wallCount = 0;
    this.doorCount = 0;
    this.roofCount = 0;
    this.torchCount = 0;
    /** @type {Set<number>} tile indices with torch=1 */
    this.torchTiles = new Set();
    /** @type {Set<number>} tile indices that carry any player-placed structure
     * (wall, door, roof, floor, or torch). Lets the wander picker bias goals
     * toward colony territory without rescanning the full grid. */
    this.structureTiles = new Set();
  }

  /** Rebuild derived wall/door/roof counts + torch/structure indices from the
   * bitmaps. Call after bulk writes that bypass the setters (save load,
   * terrain init). */
  recomputeCounts() {
    let w = 0;
    let d = 0;
    let r = 0;
    let t = 0;
    this.torchTiles.clear();
    this.structureTiles.clear();
    for (let k = 0; k < this.wall.length; k++) {
      const hasWall = this.wall[k] !== 0;
      const hasDoor = this.door[k] !== 0;
      const hasRoof = this.roof[k] !== 0;
      const hasTorch = this.torch[k] !== 0;
      const hasFloor = this.floor[k] !== 0;
      const hasRamp = this.ramp[k] !== 0;
      if (hasWall) w++;
      if (hasDoor) d++;
      if (hasRoof) r++;
      if (hasTorch) {
        t++;
        this.torchTiles.add(k);
      }
      if (hasWall || hasDoor || hasRoof || hasTorch || hasFloor || hasRamp) {
        this.structureTiles.add(k);
      }
    }
    this.wallCount = w;
    this.doorCount = d;
    this.roofCount = r;
    this.torchCount = t;
  }

  /** True iff tile (i,j) holds any player-placed structure. */
  #hasAnyStructure(k) {
    return (
      this.wall[k] !== 0 ||
      this.door[k] !== 0 ||
      this.roof[k] !== 0 ||
      this.floor[k] !== 0 ||
      this.torch[k] !== 0 ||
      this.ramp[k] !== 0
    );
  }

  /** Called by the structure setters after they mutate a bitmap. Keeps
   * structureTiles in sync without each setter spelling out the union. */
  #refreshStructureTile(k) {
    if (this.#hasAnyStructure(k)) this.structureTiles.add(k);
    else this.structureTiles.delete(k);
  }

  /** @param {number} i @param {number} j */
  isBlocked(i, j) {
    const k = this.idx(i, j);
    return this.occupancy[k] !== 0 || this.wall[k] !== 0;
  }

  /** @param {number} i @param {number} j */
  blockTile(i, j) {
    this.occupancy[this.idx(i, j)] = 1;
  }

  /** @param {number} i @param {number} j */
  unblockTile(i, j) {
    this.occupancy[this.idx(i, j)] = 0;
  }

  /** @param {number} i @param {number} j */
  isStockpile(i, j) {
    return this.stockpile[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setStockpile(i, j, v) {
    this.stockpile[this.idx(i, j)] = v ? 1 : 0;
  }

  /** @param {number} i @param {number} j */
  isWall(i, j) {
    return this.wall[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setWall(i, j, v) {
    const k = this.idx(i, j);
    const was = this.wall[k];
    const now = v ? 1 : 0;
    if (was === now) return;
    this.wall[k] = now;
    this.wallCount += now - was;
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  isDoor(i, j) {
    return this.door[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setDoor(i, j, v) {
    const k = this.idx(i, j);
    const was = this.door[k];
    const now = v ? 1 : 0;
    if (was === now) return;
    this.door[k] = now;
    this.doorCount += now - was;
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  isTorch(i, j) {
    return this.torch[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setTorch(i, j, v) {
    const k = this.idx(i, j);
    const was = this.torch[k];
    const now = v ? 1 : 0;
    if (was === now) return;
    this.torch[k] = now;
    if (now) {
      this.torchTiles.add(k);
      this.torchCount++;
    } else {
      this.torchTiles.delete(k);
      this.torchCount--;
    }
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  isRoof(i, j) {
    return this.roof[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setRoof(i, j, v) {
    const k = this.idx(i, j);
    const was = this.roof[k];
    const now = v ? 1 : 0;
    if (was === now) return;
    this.roof[k] = now;
    this.roofCount += now - was;
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  isIgnoreRoof(i, j) {
    return this.ignoreRoof[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setIgnoreRoof(i, j, v) {
    this.ignoreRoof[this.idx(i, j)] = v ? 1 : 0;
  }

  /** @param {number} i @param {number} j */
  isFloor(i, j) {
    return this.floor[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setFloor(i, j, v) {
    const k = this.idx(i, j);
    this.floor[k] = v ? 1 : 0;
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  isRamp(i, j) {
    return this.ramp[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setRamp(i, j, v) {
    const k = this.idx(i, j);
    this.ramp[k] = v ? 1 : 0;
    this.#refreshStructureTile(k);
  }

  /** @param {number} i @param {number} j */
  getFarmZone(i, j) {
    return this.farmZone[this.idx(i, j)];
  }

  /** @param {number} i @param {number} j @param {number} cropId */
  setFarmZone(i, j, cropId) {
    this.farmZone[this.idx(i, j)] = cropId & 0xff;
  }

  /** @param {number} i @param {number} j */
  isTilled(i, j) {
    return this.tilled[this.idx(i, j)] !== 0;
  }

  /** @param {number} i @param {number} j @param {number} v */
  setTilled(i, j, v) {
    this.tilled[this.idx(i, j)] = v ? 1 : 0;
  }

  /** @param {number} i @param {number} j */
  getLight(i, j) {
    return this.light[this.idx(i, j)];
  }

  /** @param {number} i @param {number} j @param {number} v */
  setLight(i, j, v) {
    this.light[this.idx(i, j)] = v;
  }

  /**
   * @param {number} i
   * @param {number} j
   */
  idx(i, j) {
    return j * this.W + i;
  }

  /** @param {number} i @param {number} j */
  inBounds(i, j) {
    return i >= 0 && j >= 0 && i < this.W && j < this.H;
  }

  /** @param {number} i @param {number} j */
  getElevation(i, j) {
    return this.elevation[this.idx(i, j)];
  }

  /** @param {number} i @param {number} j @param {number} v */
  setElevation(i, j, v) {
    this.elevation[this.idx(i, j)] = v;
  }

  /** @param {number} i @param {number} j */
  getBiome(i, j) {
    return this.biome[this.idx(i, j)];
  }

  /** @param {number} i @param {number} j @param {number} v */
  setBiome(i, j, v) {
    this.biome[this.idx(i, j)] = v;
  }

  /**
   * Flat index into the skirted (extended) buffers. Accepts i ∈ [-S, W+S),
   * j ∈ [-S, H+S). Intended for the tile-mesh renderer; gameplay code
   * should keep using `idx`/`getElevation`/`getBiome` on the inner rect.
   */
  skirtIdx(i, j) {
    return (j + SKIRT_TILES) * this.skirtW + (i + SKIRT_TILES);
  }

  /** Extended biome at (i, j). i,j ranges as in `skirtIdx`. */
  getSkirtBiome(i, j) {
    return this.skirtBiome[this.skirtIdx(i, j)];
  }

  /** Extended elevation at (i, j). i,j ranges as in `skirtIdx`. */
  getSkirtElevation(i, j) {
    return this.skirtElevation[this.skirtIdx(i, j)];
  }

  /**
   * Paint biomes using a low-frequency sin/cos field so stone/sand land in
   * coherent patches instead of salt-and-pepper, then lay a stepped heightmap
   * over the non-water tiles. Water biomes + sand stay pinned at Y=0 (the
   * water plane) so the shoreline sits flat; grass / dirt / stone rise in
   * `TERRAIN_STEP` (0.75m) increments up to `MAX_TERRAIN_STEPS`.
   */
  generateTerrain() {
    const bands = 8;
    const TAU = Math.PI * 2;
    // Per-call random phase offsets so every world refresh yields a visibly
    // different biome layout + heightmap while keeping the sin/cos field
    // shape (and therefore the stepped/coherent look).
    const biomePhase = {
      a: Math.random() * TAU,
      b: Math.random() * TAU,
      c: Math.random() * TAU,
      d: Math.random() * TAU,
      e: Math.random() * TAU,
    };
    const heightPhase = {
      a: Math.random() * TAU,
      b: Math.random() * TAU,
      c: Math.random() * TAU,
    };
    const W = this.W;
    const H = this.H;
    const EW = this.skirtW;
    const EH = this.skirtH;
    const S = SKIRT_TILES;

    // 1. Paint biomes over the extended range. fx/fz are measured against
    //    the inner grid dims, so the noise field continues smoothly across
    //    the inner ↔ skirt boundary. One medium-frequency octave nudges
    //    shorelines off perfect ovals, plus a low-amplitude product term
    //    for gentle shape variety without sharp threshold zigzags.
    for (let ej = 0; ej < EH; ej++) {
      for (let ei = 0; ei < EW; ei++) {
        const k = ej * EW + ei;
        const i = ei - S;
        const j = ej - S;
        const fx = i / W;
        const fz = j / H;
        const n =
          bands * Math.sin(fx * 6.28 + biomePhase.a) * Math.cos(fz * 6.28 + biomePhase.b) +
          bands * 0.4 * Math.sin(fx * 18 + fz * 11 + biomePhase.c) +
          bands *
            0.14 *
            Math.sin(fx * 24 + fz * 19 + biomePhase.d) *
            Math.cos(fx * 15 + fz * 17 + biomePhase.e);
        if (n > bands * 0.6) this.skirtBiome[k] = BIOME.STONE;
        else if (n < -bands * 0.4) this.skirtBiome[k] = BIOME.SAND;
        else if (Math.random() < 0.05) this.skirtBiome[k] = BIOME.DIRT;
        else this.skirtBiome[k] = BIOME.GRASS;
      }
    }

    // 2. Carve lakes on the extended buffer so water patches spanning the
    //    inner/skirt boundary stay contiguous.
    carveWaterLakes(this.skirtBiome, EW, EH);
    carveDeepWater(this.skirtBiome, EW, EH);

    // 3. BFS Chebyshev distance-to-water over the extended biome. Used to
    //    smooth heightmap cliffs that would otherwise plunge straight into
    //    shallow water from a tall interior plateau.
    const distToWater = new Int16Array(EW * EH);
    distToWater.fill(32767);
    /** @type {number[]} */
    const queue = [];
    for (let k = 0; k < this.skirtBiome.length; k++) {
      if (isWaterBiome(this.skirtBiome[k])) {
        distToWater[k] = 0;
        queue.push(k);
      }
    }
    for (let head = 0; head < queue.length; head++) {
      const k = queue[head];
      const d = distToWater[k];
      const ei = k % EW;
      const ej = (k - ei) / EW;
      for (let dj = -1; dj <= 1; dj++) {
        for (let di = -1; di <= 1; di++) {
          if (di === 0 && dj === 0) continue;
          const ni = ei + di;
          const nj = ej + dj;
          if (ni < 0 || nj < 0 || ni >= EW || nj >= EH) continue;
          const nk = nj * EW + ni;
          if (distToWater[nk] > d + 1) {
            distToWater[nk] = d + 1;
            queue.push(nk);
          }
        }
      }
    }

    // 4. Heightmap over the extended range with lake-proximity capping.
    //    `cap = (d - 1) * 2` steps gives ~1 tile ≈ 1.5m of rise per ring
    //    around water, so you can't get a 10m cliff directly over a lake.
    for (let ej = 0; ej < EH; ej++) {
      for (let ei = 0; ei < EW; ei++) {
        const k = ej * EW + ei;
        const b = this.skirtBiome[k];
        if (b === BIOME.DEEP_WATER) {
          this.skirtElevation[k] = -TERRAIN_STEP;
          continue;
        }
        if (b === BIOME.SHALLOW_WATER) {
          this.skirtElevation[k] = 0;
          continue;
        }
        if (b === BIOME.SAND) {
          const adj =
            (ei > 0 && this.skirtBiome[k - 1] === BIOME.SHALLOW_WATER) ||
            (ei < EW - 1 && this.skirtBiome[k + 1] === BIOME.SHALLOW_WATER) ||
            (ej > 0 && this.skirtBiome[k - EW] === BIOME.SHALLOW_WATER) ||
            (ej < EH - 1 && this.skirtBiome[k + EW] === BIOME.SHALLOW_WATER);
          this.skirtElevation[k] = adj ? 0 : TERRAIN_STEP;
          continue;
        }
        const i = ei - S;
        const j = ej - S;
        const fx = i / W;
        const fz = j / H;
        const h =
          Math.sin(fx * 7.5 + heightPhase.a) * Math.cos(fz * 6.8 + heightPhase.b) +
          0.5 * Math.sin(fx * 17 + fz * 13 + heightPhase.c);
        const norm = (h + 1.5) / 3;
        let steps = Math.floor(norm * (MAX_TERRAIN_STEPS + 1));
        if (steps < 0) steps = 0;
        else if (steps > MAX_TERRAIN_STEPS) steps = MAX_TERRAIN_STEPS;
        const d = distToWater[k];
        if (d < 32767) {
          const cap = Math.max(0, (d - 1) * 2);
          if (steps > cap) steps = cap;
        }
        this.skirtElevation[k] = steps * TERRAIN_STEP;
      }
    }

    // 5. Copy inner rect out of the extended buffers so W×H views stay
    //    authoritative. Flowers are rolled here (inner only) since they're
    //    a cosmetic per-tile attribute, not part of the noise field.
    this.flower.fill(0);
    for (let j = 0; j < H; j++) {
      for (let i = 0; i < W; i++) {
        const innerK = this.idx(i, j);
        const skirtK = this.skirtIdx(i, j);
        this.biome[innerK] = this.skirtBiome[skirtK];
        this.elevation[innerK] = this.skirtElevation[skirtK];
        if (this.biome[innerK] === BIOME.GRASS && Math.random() < 0.02) {
          this.flower[innerK] = 1 + Math.floor(Math.random() * 5);
        }
      }
    }

    // 6. Extend water + sand rings off the map edge. For each skirt tile
    //    outside the inner W×H, project to the nearest inner-edge tile
    //    (Chebyshev clamp). Water at the inner edge always extends; sand
    //    only extends over grass/dirt/stone so we don't overwrite a skirt
    //    water tile that the noise + carve already produced (that carved
    //    water is the natural lake continuation and beats a forced beach).
    for (let ej = -S; ej < H + S; ej++) {
      for (let ei = -S; ei < W + S; ei++) {
        if (ei >= 0 && ei < W && ej >= 0 && ej < H) continue;
        const ci = Math.max(0, Math.min(W - 1, ei));
        const cj = Math.max(0, Math.min(H - 1, ej));
        const innerK = this.idx(ci, cj);
        const innerBiome = this.biome[innerK];
        const skirtK = this.skirtIdx(ei, ej);
        if (isWaterBiome(innerBiome)) {
          this.skirtBiome[skirtK] = innerBiome;
          this.skirtElevation[skirtK] = this.elevation[innerK];
        } else if (innerBiome === BIOME.SAND) {
          const current = this.skirtBiome[skirtK];
          if (current === BIOME.GRASS || current === BIOME.DIRT || current === BIOME.STONE) {
            this.skirtBiome[skirtK] = innerBiome;
            this.skirtElevation[skirtK] = this.elevation[innerK];
          }
        }
      }
    }

    this.hasSkirt = true;
  }
}
